version: '3.7'
 
services:
  api:
    build: backend
    restart: always
    ports:
      - 8080:8080
  # gitlab-runner:
  #   container_name: gitlab-runner
  #   image: gitlab/gitlab-runner:latest
  #   restart: always
  #   volumes:
  #     - './runner-data:/home/gitlab_ci_multi_runner/data'
  #     - './runner-config:/etc/gitlab-runner'
  #     - '/var/run/docker.sock:/var/run/docker.sock:rw'
  #   networks:
  #     gitlab-networks:
  #       ipv4_address: 10.5.0.3
